import { createClient } from '@/lib/supabase/client'
import { hmacFingerprint } from '@/lib/crypto/vault'
import { toEncryptedColumns } from '@/lib/crypto/encryptedRow'
import { syncTagsByName } from '@/lib/services/tags'
import { getCategories } from '@/lib/services/categories'
import type { LinkContent } from '@/lib/services/links'
import type { LinkStatus } from '@/lib/types/database'

/**
 * Dev-only sample data, restoring what supabase/migrations/0003_seed_mock_links.sql
 * used to provide before 0010_encryption.sql wiped it (plaintext mock data can't be
 * retroactively encrypted from SQL). Only ever called for test@linkvault.dev -- see
 * VaultContext.unlock().
 */

const MOCK_TAG_NAMES = [
  'react', 'frontend', 'nextjs', 'framework', 'typescript', 'docs', 'rsc', 'design',
  'ui', 'css', 'flexbox', 'reference', 'tips', 'supabase', 'auth', 'backend',
  'ai', 'rust', 'devops', 'docker', 'kubernetes', 'testing', 'performance', 'accessibility',
  'animation', 'tailwind', 'nodejs', 'database', 'graphql', 'api', 'security', 'architecture',
  'career', 'productivity', 'git', 'javascript', 'algorithms', 'interviews', 'svelte', 'mobile',
  'open-source', 'tools', 'postgres',
]

type MockLinkSeed = {
  url: string
  title: string
  description: string
  siteName: string
  categoryName: string
  notes: string | null
  status: LinkStatus
  isFavorite: boolean
  createdAt: string
  tags: string[]
  deletedAt?: string
}

const MOCK_LINKS: MockLinkSeed[] = [
  // ── YouTube (28 links) ──────────────────────────────────
  { url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', title: 'React 19 Deep Dive — New Features Explained', description: 'A comprehensive walkthrough of everything new in React 19 including Server Components, Actions, and the new hooks.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-10T10:00:00Z', tags: ['react', 'frontend'] },
  { url: 'https://www.youtube.com/watch?v=aB2cD3eF4gH', title: 'Next.js App Router — Complete Course 2026', description: 'Four-hour deep dive into the Next.js App Router: layouts, loading states, error boundaries, server actions, and deployment.', siteName: 'youtube.com', categoryName: 'YouTube', notes: 'Bookmark 1:22:00 for the caching section', status: 'watching', isFavorite: true, createdAt: '2026-05-15T09:00:00Z', tags: ['nextjs', 'react', 'frontend'] },
  { url: 'https://www.youtube.com/watch?v=iJ5kL6mN7oP', title: 'Tailwind CSS v4 — What Changed and Why It Matters', description: 'Overview of the new engine, faster JIT, CSS-first config, and the migration path from v3.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-20T14:00:00Z', tags: ['tailwind', 'css'], deletedAt: '2026-03-10T08:00:00Z' },
  { url: 'https://www.youtube.com/watch?v=qR8sT9uV0wX', title: 'Supabase Crash Course — Auth, DB, Storage in 90 Minutes', description: 'Build a full-stack app from scratch using Supabase for auth, PostgreSQL for data, and Storage for files.', siteName: 'youtube.com', categoryName: 'YouTube', notes: 'Great for showing the team', status: 'watching', isFavorite: false, createdAt: '2026-03-12T11:00:00Z', tags: ['supabase', 'backend', 'database'] },
  { url: 'https://www.youtube.com/watch?v=yZ0aB1cD2eF', title: 'Building AI Apps with the Vercel AI SDK', description: 'Stream LLM responses, handle tool calls, and persist chat history using the Vercel AI SDK with Next.js.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-02T16:00:00Z', tags: ['ai', 'frontend', 'nextjs'] },
  { url: 'https://www.youtube.com/watch?v=gH3iJ4kL5mN', title: 'Rust for JavaScript Developers', description: 'Side-by-side comparison of Rust and JS concepts: ownership vs. garbage collection, traits vs. interfaces, and cargo vs. npm.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-02-28T10:30:00Z', tags: ['rust', 'backend'] },
  { url: 'https://www.youtube.com/watch?v=oP6qR7sT8uV', title: 'System Design Interview Patterns — Top 10', description: 'Covers rate limiting, URL shortening, distributed caching, message queues, and more with diagrams.', siteName: 'youtube.com', categoryName: 'YouTube', notes: 'Must review before interviews', status: 'watching', isFavorite: true, createdAt: '2026-01-15T08:00:00Z', tags: ['architecture', 'interviews', 'career'] },
  { url: 'https://www.youtube.com/watch?v=wX0yZ1aB2cD', title: 'CSS Animations Masterclass — From Basics to GSAP', description: 'Transitions, keyframes, scroll-driven animations, and how to orchestrate complex sequences with GSAP.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'read', isFavorite: false, createdAt: '2025-12-05T15:00:00Z', tags: ['css', 'animation', 'frontend'] },
  { url: 'https://www.youtube.com/watch?v=eF3gH4iJ5kL', title: 'Docker for Developers — Full Course', description: 'Containers, images, volumes, Docker Compose, and how to containerize a Next.js + Postgres stack.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-01T10:00:00Z', tags: ['docker', 'devops'], deletedAt: '2026-04-22T11:30:00Z' },
  { url: 'https://www.youtube.com/watch?v=mN6oP7qR8sT', title: 'How Git Works Internally', description: 'Explore the .git directory, DAGs, pack files, and refs. Understanding Git internals makes conflicts trivial.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'read', isFavorite: true, createdAt: '2025-11-20T12:00:00Z', tags: ['git', 'tools'] },
  { url: 'https://www.youtube.com/watch?v=uV9wX0yZ1aB', title: 'GraphQL vs REST — When to Use Each', description: 'Honest comparison of DX, performance, caching, and real-world trade-offs with live code examples.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'read', isFavorite: false, createdAt: '2025-10-08T13:00:00Z', tags: ['graphql', 'api', 'backend'] },
  { url: 'https://www.youtube.com/watch?v=cD2eF3gH4iJ', title: 'PostgreSQL Performance Tuning — Indexes, EXPLAIN, and Vacuuming', description: 'How to find slow queries, choose the right index type, and keep autovacuum healthy in production.', siteName: 'youtube.com', categoryName: 'YouTube', notes: 'Covers the partial index trick we need', status: 'watching', isFavorite: false, createdAt: '2026-03-25T09:30:00Z', tags: ['postgres', 'database', 'performance'] },
  { url: 'https://www.youtube.com/watch?v=kL5mN6oP7qR', title: 'Building a Design System from Scratch', description: 'Tokens, component API design, Storybook setup, and publishing to npm — the full workflow explained.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-08T11:00:00Z', tags: ['design', 'ui', 'frontend'] },
  { url: 'https://www.youtube.com/watch?v=sT8uV9wX0yZ', title: 'The Future of AI in Software Development', description: 'Panel discussion on AI pair programmers, autonomous agents, and where human engineers will focus in 5 years.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-20T17:00:00Z', tags: ['ai', 'career'] },
  { url: 'https://www.youtube.com/watch?v=aB1cD2eF3gH', title: 'SvelteKit vs Next.js — Honest Comparison in 2026', description: 'DX, performance, routing, SSR, and ecosystem maturity compared through building the same app twice.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-04-10T10:00:00Z', tags: ['svelte', 'nextjs', 'frontend'] },
  { url: 'https://www.youtube.com/watch?v=iJ4kL5mN6oP', title: 'Web Accessibility from Zero — Screen Readers, ARIA, and Testing', description: 'Practical accessibility: semantic HTML, ARIA roles, keyboard traps, and using axe-core in CI.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-02-14T14:00:00Z', tags: ['accessibility', 'frontend'] },
  { url: 'https://www.youtube.com/watch?v=qR7sT8uV9wX', title: 'Kubernetes for Developers — Not Just for Ops', description: 'Pods, deployments, services, ingress, and how to run local k8s with minikube as a dev environment.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-01-30T09:00:00Z', tags: ['kubernetes', 'devops'] },
  { url: 'https://www.youtube.com/watch?v=yZ0aB1cD3eF', title: 'Vim Motions in VS Code — Productivity Unlocked', description: 'Practical Vim motions you can learn in a weekend that will permanently speed up your editing.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'read', isFavorite: true, createdAt: '2025-09-15T11:00:00Z', tags: ['tools', 'productivity'] },
  { url: 'https://www.youtube.com/watch?v=gH4iJ5kL6mN', title: 'Live Senior Dev Interview — Real Coding Session', description: 'Unedited recording of a senior frontend interview: system design, take-home review, and live coding.', siteName: 'youtube.com', categoryName: 'YouTube', notes: 'Watch before interviews', status: 'watching', isFavorite: true, createdAt: '2026-04-28T15:00:00Z', tags: ['career', 'interviews'] },
  { url: 'https://www.youtube.com/watch?v=oP6qR7sT9uV', title: 'Advanced TypeScript Patterns You Actually Use', description: 'Conditional types, mapped types, template literals, and infer — with real-world use cases not toy examples.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-05T10:00:00Z', tags: ['typescript', 'frontend'] },
  { url: 'https://www.youtube.com/watch?v=wX1yZ2aB3cD', title: 'Bun vs Node.js — Real Benchmarks in 2026', description: 'Startup time, HTTP throughput, file I/O, and SQLite benchmarks comparing Bun 1.2 and Node 22.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-18T08:00:00Z', tags: ['nodejs', 'performance', 'tools'] },
  { url: 'https://www.youtube.com/watch?v=eF3gH5iJ6kL', title: 'React Testing Library — The Right Mental Model', description: 'Why RTL tests behavior and not implementation, and how to write tests that survive refactors.', siteName: 'youtube.com', categoryName: 'YouTube', notes: 'Great for onboarding new devs', status: 'read', isFavorite: false, createdAt: '2025-08-20T13:00:00Z', tags: ['testing', 'react', 'frontend'] },
  { url: 'https://www.youtube.com/watch?v=mN7oP8qR9sT', title: 'tRPC End-to-End Type Safety in 30 Minutes', description: 'Set up tRPC with Next.js, define routers, call procedures from the client, and handle errors.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-05T16:00:00Z', tags: ['typescript', 'api', 'backend'] },
  { url: 'https://www.youtube.com/watch?v=uV0wX1yZ2aB', title: 'Edge Computing Explained — Vercel, Cloudflare, and Deno Deploy', description: 'What edge functions are, when to use them, and the cold start / latency trade-offs.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'read', isFavorite: false, createdAt: '2025-11-10T10:00:00Z', tags: ['backend', 'performance'] },
  { url: 'https://www.youtube.com/watch?v=cD3eF4gH5iJ', title: 'CSS Grid Mastery — Every Property Explained', description: 'Named template areas, subgrid, auto-placement algorithm, and responsive layouts without media queries.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'read', isFavorite: false, createdAt: '2025-10-22T11:00:00Z', tags: ['css', 'frontend', 'reference'] },
  { url: 'https://www.youtube.com/watch?v=kL6mN7oP8qR', title: 'Drizzle ORM — Better Than Prisma?', description: 'Type-safe SQL queries, schema migrations, and how Drizzle compares to Prisma in DX and performance.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-03-01T14:00:00Z', tags: ['database', 'backend', 'typescript'] },
  { url: 'https://www.youtube.com/watch?v=sT9uV0wX1yZ', title: 'Building a CLI Tool with TypeScript and Bun', description: 'Argument parsing, interactive prompts, file system operations, and publishing to npm.', siteName: 'youtube.com', categoryName: 'YouTube', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-22T09:00:00Z', tags: ['typescript', 'nodejs', 'tools'] },
  { url: 'https://www.youtube.com/watch?v=aB2cD3eF5gH', title: 'Web Performance in 2026 — Core Web Vitals Deep Dive', description: 'LCP, CLS, INP explained with real profiling sessions and fixes for common Next.js performance regressions.', siteName: 'youtube.com', categoryName: 'YouTube', notes: 'LCP section is gold', status: 'watching', isFavorite: true, createdAt: '2026-05-25T10:00:00Z', tags: ['performance', 'frontend', 'nextjs'] },

  // ── GitHub (15 links) ───────────────────────────────────
  { url: 'https://github.com/vercel/next.js', title: 'Next.js — The React Framework for the Web', description: 'The React framework for the Web used by some of the world\'s largest companies. Enables high-quality web applications with the power of React.', siteName: 'github.com', categoryName: 'GitHub', notes: 'Track for Next.js 16 updates', status: 'watching', isFavorite: true, createdAt: '2026-05-09T08:00:00Z', tags: ['nextjs', 'react', 'framework'] },
  { url: 'https://github.com/shadcn-ui/ui', title: 'shadcn/ui — Beautifully Designed Components', description: 'Copy-paste components built with Radix UI and Tailwind. Not a library — your code, your rules.', siteName: 'github.com', categoryName: 'GitHub', notes: 'Check out the new sidebar component', status: 'watching', isFavorite: true, createdAt: '2026-04-15T10:00:00Z', tags: ['ui', 'design', 'react'] },
  { url: 'https://github.com/tailwindlabs/tailwindcss', title: 'Tailwind CSS — A Utility-First CSS Framework', description: 'Rapidly build modern websites without ever leaving your HTML. The v4 rewrite is built on a native CSS engine.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-03-20T09:00:00Z', tags: ['tailwind', 'css', 'frontend'] },
  { url: 'https://github.com/supabase/supabase', title: 'Supabase — The Open Source Firebase Alternative', description: 'Auth, database, storage, realtime, and edge functions. Built on Postgres.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'watching', isFavorite: true, createdAt: '2026-02-10T11:00:00Z', tags: ['supabase', 'backend', 'database'] },
  { url: 'https://github.com/trpc/trpc', title: 'tRPC — End-to-End Type Safety Without Schema', description: 'Move fast and break nothing. Full-stack TypeScript without code generation or runtime bloat.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-02T14:00:00Z', tags: ['typescript', 'api', 'backend'], deletedAt: '2026-02-14T09:00:00Z' },
  { url: 'https://github.com/colinhacks/zod', title: 'Zod — TypeScript-First Schema Validation', description: 'Declare a validator once and Zod infers the static TypeScript type. Works beautifully with tRPC and React Hook Form.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'read', isFavorite: false, createdAt: '2025-12-01T10:00:00Z', tags: ['typescript', 'tools', 'backend'] },
  { url: 'https://github.com/TanStack/query', title: 'TanStack Query — Powerful Async State Management', description: 'Fetch, cache, synchronize, and update server state in your web applications. Formerly React Query.', siteName: 'github.com', categoryName: 'GitHub', notes: 'Upgrade notes for v6', status: 'watching', isFavorite: true, createdAt: '2026-01-20T09:00:00Z', tags: ['react', 'frontend', 'tools'] },
  { url: 'https://github.com/drizzle-team/drizzle-orm', title: 'Drizzle ORM — Type-Safe SQL for TypeScript', description: 'Headless ORM for TypeScript. Write SQL-like queries with full type inference and zero magic.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-03-08T13:00:00Z', tags: ['database', 'typescript', 'open-source'] },
  { url: 'https://github.com/lucia-auth/lucia', title: 'Lucia — Auth for the Modern Web', description: 'Framework-agnostic authentication library for TypeScript. Works with any database adapter.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-18T10:00:00Z', tags: ['auth', 'backend', 'security'] },
  { url: 'https://github.com/honojs/hono', title: 'Hono — Ultrafast Web Framework for the Edges', description: 'Small, simple, and ultrafast. Works on Cloudflare Workers, Deno, Bun, AWS Lambda, and Node.js.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-01T11:00:00Z', tags: ['backend', 'api', 'nodejs'] },
  { url: 'https://github.com/oven-sh/bun', title: 'Bun — Fast All-in-One JavaScript Runtime', description: 'JavaScript runtime, package manager, bundler, and test runner. Drop-in Node.js replacement with native TypeScript.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-03-15T09:00:00Z', tags: ['nodejs', 'tools', 'performance'] },
  { url: 'https://github.com/withastro/astro', title: 'Astro — The Web Framework for Content-Driven Websites', description: 'Zero JS by default, islands architecture, and works with React, Svelte, Vue, and Solid components.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'read', isFavorite: false, createdAt: '2025-11-05T14:00:00Z', tags: ['frontend', 'framework'] },
  { url: 'https://github.com/expo/expo', title: 'Expo — React Native Platform', description: 'Build universal native apps for iOS, Android, and web with a single React codebase.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-02-20T10:00:00Z', tags: ['mobile', 'react'] },
  { url: 'https://github.com/langchain-ai/langchainjs', title: 'LangChain.js — Build LLM Applications', description: 'Framework for building AI applications: chains, agents, RAG pipelines, and tool use for JavaScript.', siteName: 'github.com', categoryName: 'GitHub', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-12T15:00:00Z', tags: ['ai', 'backend'] },
  { url: 'https://github.com/biomejs/biome', title: 'Biome — Formatter and Linter for the Web', description: 'A fast formatter and linter for JavaScript, TypeScript, JSON, and CSS. Drop-in Prettier + ESLint replacement.', siteName: 'github.com', categoryName: 'GitHub', notes: 'Try replacing ESLint in this project', status: 'unread', isFavorite: false, createdAt: '2026-04-25T09:00:00Z', tags: ['tools', 'typescript', 'frontend'] },

  // ── Articles (20 links) ─────────────────────────────────
  { url: 'https://javascript.info/closure', title: 'JavaScript Closures — The Complete Picture', description: 'Lexical environment, closure scope, and practical patterns like module factories and memoization.', siteName: 'javascript.info', categoryName: 'Article', notes: null, status: 'read', isFavorite: false, createdAt: '2025-09-10T11:00:00Z', tags: ['javascript', 'frontend', 'reference'] },
  { url: 'https://css-tricks.com/a-complete-guide-to-flexbox/', title: 'A Complete Guide to Flexbox', description: 'A comprehensive reference for the CSS flexbox layout module, with visual examples for every property and combination.', siteName: 'css-tricks.com', categoryName: 'Article', notes: null, status: 'read', isFavorite: false, createdAt: '2026-05-06T11:00:00Z', tags: ['css', 'flexbox', 'reference'] },
  { url: 'https://www.typescriptlang.org/docs/', title: 'TypeScript Official Documentation', description: 'Official TypeScript documentation covering all language features, the type system, and configuration options.', siteName: 'typescriptlang.org', categoryName: 'Course', notes: null, status: 'read', isFavorite: false, createdAt: '2026-05-08T12:00:00Z', tags: ['typescript', 'docs'] },
  { url: 'https://supabase.com/docs/guides/auth/server-side/nextjs', title: 'Supabase Auth — SSR Guide for Next.js', description: 'Complete guide to authentication with Supabase in server-side rendered apps, covering cookie management and RLS.', siteName: 'supabase.com', categoryName: 'Article', notes: 'Check the new SSR section', status: 'archived', isFavorite: false, createdAt: '2026-05-05T14:00:00Z', tags: ['supabase', 'auth', 'backend'], deletedAt: '2026-05-01T16:00:00Z' },
  { url: 'https://tailwindcss.com/blog/tailwindcss-v4', title: 'Tailwind CSS v4 — Migration Guide', description: 'Breaking changes, new config format, the oxide engine upgrade, and a step-by-step migration from v3.', siteName: 'tailwindcss.com', categoryName: 'Article', notes: null, status: 'read', isFavorite: false, createdAt: '2026-01-08T10:00:00Z', tags: ['tailwind', 'css', 'frontend'] },
  { url: 'https://web.dev/articles/css-container-queries', title: 'CSS Container Queries — A Practical Guide', description: 'Why container queries change how you think about responsive components, with copy-paste examples.', siteName: 'web.dev', categoryName: 'Article', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-14T13:00:00Z', tags: ['css', 'frontend'] },
  { url: 'https://www.smashingmagazine.com/2026/01/building-accessible-forms/', title: 'Building Accessible Forms — The Definitive Guide', description: 'Labels, error messaging, focus management, ARIA, and testing your forms with a screen reader.', siteName: 'smashingmagazine.com', categoryName: 'Article', notes: null, status: 'read', isFavorite: false, createdAt: '2026-01-22T11:00:00Z', tags: ['accessibility', 'frontend', 'ui'] },
  { url: 'https://auth0.com/blog/oauth2-oidc-explained/', title: 'OAuth 2.0 and OIDC Explained — Once and for All', description: 'Authorization vs. authentication, flows (PKCE, client credentials, device), and JWTs demystified.', siteName: 'auth0.com', categoryName: 'Article', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-03-05T10:00:00Z', tags: ['auth', 'security', 'backend'] },
  { url: 'https://2025.stateofjs.com/', title: 'The State of JavaScript 2025', description: 'Annual survey results: which libraries devs love or dread, meta-frameworks, runtimes, and what\'s coming next.', siteName: 'stateofjs.com', categoryName: 'Article', notes: null, status: 'read', isFavorite: true, createdAt: '2026-01-15T09:00:00Z', tags: ['javascript', 'frontend', 'reference'] },
  { url: 'https://swyx.io/learn-in-public', title: 'Learn in Public — The Fastest Way to Learn', description: 'Write about what you learn, even if you\'re wrong. The community corrects you and you level up faster.', siteName: 'swyx.io', categoryName: 'Article', notes: null, status: 'read', isFavorite: true, createdAt: '2025-10-01T10:00:00Z', tags: ['career', 'productivity'] },
  { url: 'https://martinfowler.com/articles/micro-frontends.html', title: 'Micro Frontends — Patterns and Anti-Patterns', description: 'When micro-frontends make sense, the integration approaches, and the shared state problem nobody talks about.', siteName: 'martinfowler.com', categoryName: 'Article', notes: null, status: 'archived', isFavorite: false, createdAt: '2025-08-10T14:00:00Z', tags: ['architecture', 'frontend'], deletedAt: '2025-09-20T14:00:00Z' },
  { url: 'https://google.github.io/eng-practices/review/', title: 'Google Engineering — Code Review Best Practices', description: 'How Google engineers think about code review: what to look for, how to give feedback, and reviewer speed.', siteName: 'google.github.io', categoryName: 'Article', notes: null, status: 'read', isFavorite: false, createdAt: '2025-11-15T11:00:00Z', tags: ['career', 'tools'] },
  { url: 'https://www.apollographql.com/blog/graphql-vs-rest', title: 'GraphQL vs REST — A Developer\'s Honest Take', description: 'After using both in production: where GraphQL shines, where REST wins, and the over-fetching myth.', siteName: 'apollographql.com', categoryName: 'Article', notes: null, status: 'read', isFavorite: false, createdAt: '2025-12-10T13:00:00Z', tags: ['graphql', 'api', 'backend'] },
  { url: 'https://thenewstack.io/rust-is-eating-systems-programming/', title: 'Rust Is Eating Systems Programming — Here Is Why', description: 'Memory safety without GC, the borrow checker as a paradigm shift, and which industries are adopting Rust fastest.', siteName: 'thenewstack.io', categoryName: 'Article', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-02-05T09:00:00Z', tags: ['rust', 'backend', 'performance'] },
  { url: 'https://dev.to/best-vscode-extensions-2026', title: '10 VS Code Extensions That Actually Make You Faster', description: 'Curated list with honest takes — no filler. Each pick includes why it beats the alternatives.', siteName: 'dev.to', categoryName: 'Article', notes: null, status: 'read', isFavorite: false, createdAt: '2026-04-30T10:00:00Z', tags: ['tools', 'productivity'] },
  { url: 'https://kentcdodds.com/blog/the-testing-trophy', title: 'The Testing Trophy — A Better Testing Strategy', description: 'Why the old pyramid is wrong, how to balance unit, integration, and e2e tests, and what to test first.', siteName: 'kentcdodds.com', categoryName: 'Article', notes: null, status: 'read', isFavorite: true, createdAt: '2025-09-20T11:00:00Z', tags: ['testing', 'career'] },
  { url: 'https://www.patterns.dev/posts/rendering-patterns', title: 'Rendering Patterns for the Modern Web', description: 'SSG, SSR, ISR, PPR, streaming — when each pattern applies and the trade-offs in latency vs. freshness.', siteName: 'patterns.dev', categoryName: 'Article', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-03T14:00:00Z', tags: ['nextjs', 'performance', 'architecture'] },
  { url: 'https://danluu.com/developer-productivity/', title: 'Developer Productivity — What Actually Moves the Needle', description: 'Evidence-based look at what makes teams fast: small PRs, CI speed, test coverage, and psychological safety.', siteName: 'danluu.com', categoryName: 'Article', notes: null, status: 'read', isFavorite: false, createdAt: '2025-10-15T10:00:00Z', tags: ['productivity', 'career'] },
  { url: 'https://www.joshwcomeau.com/css/styled-components/', title: 'The Styled Components Pitfall (and How to Avoid It)', description: 'Performance implications of CSS-in-JS at scale, SSR hydration costs, and the move back to utility classes.', siteName: 'joshwcomeau.com', categoryName: 'Article', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-22T11:00:00Z', tags: ['css', 'frontend', 'performance'] },
  { url: 'https://interviewing.io/blog/how-to-pass-a-senior-dev-interview', title: 'How to Pass a Senior Developer Interview in 2026', description: 'Communication patterns, system design expectations, and the behavioral questions that actually trip people up.', siteName: 'interviewing.io', categoryName: 'Article', notes: 'Share with team', status: 'watching', isFavorite: false, createdAt: '2026-05-14T09:00:00Z', tags: ['career', 'interviews'] },

  // ── Courses (10 links) ──────────────────────────────────
  { url: 'https://www.theodinproject.com/', title: 'The Odin Project — Full Stack Open Curriculum', description: 'Free, community-maintained full-stack curriculum covering HTML, CSS, JavaScript, Node.js, and React.', siteName: 'theodinproject.com', categoryName: 'Course', notes: null, status: 'watching', isFavorite: false, createdAt: '2025-08-01T10:00:00Z', tags: ['frontend', 'backend', 'docs'] },
  { url: 'https://css-for-js.dev/', title: 'CSS for JavaScript Developers — Josh Comeau', description: 'Deep course that finally makes CSS click for JS devs. Flow layout, flexbox, grid, and animations.', siteName: 'css-for-js.dev', categoryName: 'Course', notes: 'Worth every penny', status: 'read', isFavorite: true, createdAt: '2025-09-01T10:00:00Z', tags: ['css', 'frontend', 'design'] },
  { url: 'https://epicreact.dev/', title: 'Epic React — Kent C. Dodds', description: 'The definitive React course. Patterns, performance, testing, and the React mental model from first principles.', siteName: 'epicreact.dev', categoryName: 'Course', notes: 'Working through module 4', status: 'watching', isFavorite: true, createdAt: '2025-10-01T10:00:00Z', tags: ['react', 'frontend', 'performance'] },
  { url: 'https://fireship.io/pro/', title: 'Fireship Pro — Modern Web Dev Short Courses', description: 'Snappy, high-density courses on modern stacks: Next.js, Svelte, Firebase, Docker, and more.', siteName: 'fireship.io', categoryName: 'Course', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-01-05T09:00:00Z', tags: ['frontend', 'tools'] },
  { url: 'https://fullstackopen.com/', title: 'Full Stack Open 2026 — University of Helsinki', description: 'Free university-level course: React, Node.js, GraphQL, TypeScript, CI/CD, containers, and React Native.', siteName: 'fullstackopen.com', categoryName: 'Course', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-02-01T10:00:00Z', tags: ['frontend', 'backend', 'docs'], deletedAt: '2026-04-05T10:00:00Z' },
  { url: 'https://learn.deeplearning.ai/langchain', title: 'LangChain for LLM Application Development', description: 'Andrew Ng\'s short course on LangChain: chains, memory, agents, and Q&A over documents.', siteName: 'learn.deeplearning.ai', categoryName: 'Course', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-03-10T11:00:00Z', tags: ['ai', 'backend'] },
  { url: 'https://frontendmasters.com/courses/react-performance/', title: 'React Performance — Frontend Masters', description: 'Profiling, memoization pitfalls, code splitting, lazy loading, and Concurrent Mode in production.', siteName: 'frontendmasters.com', categoryName: 'Course', notes: null, status: 'read', isFavorite: false, createdAt: '2025-11-01T10:00:00Z', tags: ['react', 'performance', 'frontend'] },
  { url: 'https://www.coursera.org/specializations/algorithms', title: 'Algorithms Specialization — Stanford on Coursera', description: 'Tim Roughgarden\'s four-course series: divide and conquer, graph search, greedy, dynamic programming, and NP.', siteName: 'coursera.org', categoryName: 'Course', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-08T09:00:00Z', tags: ['algorithms', 'career', 'interviews'] },
  { url: 'https://www.executivebible.io/postgres', title: 'PostgreSQL for Application Developers', description: 'Row-level security, JSONB, full-text search, triggers, and partitioning for app developers not DBAs.', siteName: 'executivebible.io', categoryName: 'Course', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-03-28T14:00:00Z', tags: ['postgres', 'database', 'backend'] },
  { url: 'https://testingjavascript.com/', title: 'Testing JavaScript — Kent C. Dodds', description: 'Unit, integration, and e2e testing with Jest, RTL, Cypress, and Playwright. How to actually test React apps.', siteName: 'testingjavascript.com', categoryName: 'Course', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-06T10:00:00Z', tags: ['testing', 'react', 'frontend'] },

  // ── Tweets (10 links) ───────────────────────────────────
  { url: 'https://x.com/dan_abramov/status/1234567890', title: 'Dan Abramov on React Server Components', description: 'Thread explaining the mental model behind React Server Components and why they matter for the future of web.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-12T15:30:00Z', tags: ['react', 'rsc'] },
  { url: 'https://x.com/leeerob/status/2345678901', title: 'Lee Robinson on Next.js 16 Release Highlights', description: 'Quick thread on what changed in 16: PPR by default, improved caching, new dev tools, and breaking changes.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-17T10:00:00Z', tags: ['nextjs', 'frontend'] },
  { url: 'https://x.com/kentcdodds/status/3456789012', title: 'Kent C. Dodds on Why He Tests Behavior Not Implementation', description: 'The retweet-worthy thread on why testing internals creates false confidence and fragile test suites.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'read', isFavorite: true, createdAt: '2026-01-10T09:00:00Z', tags: ['testing', 'frontend', 'career'] },
  { url: 'https://x.com/t3dotgg/status/4567890123', title: 'Theo on Why TypeScript Strict Mode Is Non-Negotiable', description: 'Thread on the specific TS strict checks that catch real bugs vs. the ones that are just noise.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'read', isFavorite: false, createdAt: '2026-02-20T11:00:00Z', tags: ['typescript', 'frontend'] },
  { url: 'https://x.com/TkDodo/status/5678901234', title: 'TkDodo on the React Query Mental Model', description: 'Why thinking of React Query as a "data fetching" library misses the point — it\'s a server state synchronizer.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'read', isFavorite: true, createdAt: '2025-12-15T13:00:00Z', tags: ['react', 'frontend'] },
  { url: 'https://x.com/shadcn/status/6789012345', title: 'shadcn on the Philosophy Behind shadcn/ui', description: 'Why the "install and own it" model beats npm packages for design systems. You should copy, not depend.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-03-18T10:00:00Z', tags: ['design', 'ui'] },
  { url: 'https://x.com/wesbos/status/7890123456', title: 'Wes Bos on New Web Platform APIs You Should Know', description: 'Thread on native View Transitions API, Popover API, and the dialog element landing in all browsers.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-12T14:00:00Z', tags: ['frontend', 'javascript'] },
  { url: 'https://x.com/sarah_edo/status/8901234567', title: 'Sarah Drasner on CSS Custom Properties as a Design Token System', description: 'Thread showing how CSS variables + @layer create a themeable component system without any JS.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'read', isFavorite: false, createdAt: '2025-10-25T11:00:00Z', tags: ['css', 'design'] },
  { url: 'https://x.com/ry/status/9012345678', title: 'Ryan Dahl on Deno 2.0 and Node.js Compatibility', description: 'The creator of Node.js explains why Deno 2.0 supports npm packages and what that means for the runtime wars.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'read', isFavorite: false, createdAt: '2025-11-05T09:00:00Z', tags: ['nodejs', 'backend'] },
  { url: 'https://x.com/kelseyhightower/status/1098765432', title: 'Kelsey Hightower on Kubernetes Maturity in 2026', description: 'Why k8s won, what still hurts, and where the simplification work is finally happening.', siteName: 'x.com', categoryName: 'Tweet', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-19T16:00:00Z', tags: ['kubernetes', 'devops'] },

  // ── Instagram (7 links) ─────────────────────────────────
  { url: 'https://www.instagram.com/p/abc123', title: 'UI Design Tips for Developers', description: 'Quick visual tips for making your interfaces look polished and professional without a design background.', siteName: 'instagram.com', categoryName: 'Instagram', notes: 'Great color palette tips in here', status: 'read', isFavorite: true, createdAt: '2026-05-07T09:00:00Z', tags: ['design', 'ui'] },
  { url: 'https://www.instagram.com/p/glassmorph456', title: 'Glassmorphism Design Inspiration Pack', description: 'A collection of frosted glass UI components with real CSS code snippets for each card and modal.', siteName: 'instagram.com', categoryName: 'Instagram', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-03-22T12:00:00Z', tags: ['design', 'css', 'ui'], deletedAt: '2026-03-29T19:00:00Z' },
  { url: 'https://www.instagram.com/p/workspace789', title: 'Developer Workspace Setup Tour', description: 'Minimal desk setup with dual monitors, custom keycaps, and the Neovim config breakdown.', siteName: 'instagram.com', categoryName: 'Instagram', notes: null, status: 'read', isFavorite: false, createdAt: '2025-12-20T10:00:00Z', tags: ['tools', 'productivity'] },
  { url: 'https://www.instagram.com/p/colortheory321', title: 'Color Theory for Developers — Cheat Sheet', description: 'Complementary, analogous, and triadic color pairs. How to build a palette from a single brand color.', siteName: 'instagram.com', categoryName: 'Instagram', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-04-05T11:00:00Z', tags: ['design', 'ui', 'frontend'] },
  { url: 'https://www.instagram.com/p/terminal654', title: 'Terminal Customization Showcase — zsh + Starship', description: 'Before/after of a terminal glow-up using Starship prompt, Tokyo Night theme, and custom aliases.', siteName: 'instagram.com', categoryName: 'Instagram', notes: null, status: 'read', isFavorite: false, createdAt: '2025-10-10T09:00:00Z', tags: ['tools', 'productivity'] },
  { url: 'https://www.instagram.com/p/figmatips987', title: 'Figma Tricks Every Developer Should Know', description: 'Component variants, auto-layout for responsive mockups, and the Dev Mode handoff workflow.', siteName: 'instagram.com', categoryName: 'Instagram', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-02-18T14:00:00Z', tags: ['design', 'tools', 'ui'] },
  { url: 'https://www.instagram.com/p/cssart159', title: 'CSS Art Gallery — 10 Pieces Made with Pure CSS', description: 'Impressively complex illustrations made with nothing but CSS. Source links included in bio.', siteName: 'instagram.com', categoryName: 'Instagram', notes: null, status: 'archived', isFavorite: false, createdAt: '2025-08-30T15:00:00Z', tags: ['css', 'design'] },

  // ── TikTok (6 links) ────────────────────────────────────
  { url: 'https://www.tiktok.com/@codewithreact/video/123456', title: '5 TypeScript Tricks You Probably Don\'t Know', description: 'Short video covering advanced TypeScript patterns that most developers miss: conditional types to template literals.', siteName: 'tiktok.com', categoryName: 'TikTok', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-05-11T20:00:00Z', tags: ['typescript', 'tips'] },
  { url: 'https://www.tiktok.com/@csswizard/video/234567', title: 'CSS One-Liner Hacks That Solve Real Problems', description: 'aspect-ratio, clamp(), :has(), and logical properties — the CSS features that replace dozens of media queries.', siteName: 'tiktok.com', categoryName: 'TikTok', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-04-16T19:00:00Z', tags: ['css', 'tips', 'frontend'] },
  { url: 'https://www.tiktok.com/@gitmasters/video/345678', title: 'Git Commands Every Developer Needs But Forgets', description: 'git stash pop, bisect, reflog, and cherry-pick with real examples of when you\'d actually use them.', siteName: 'tiktok.com', categoryName: 'TikTok', notes: null, status: 'read', isFavorite: false, createdAt: '2025-11-25T20:00:00Z', tags: ['git', 'tips', 'tools'] },
  { url: 'https://www.tiktok.com/@linuxdaily/video/456789', title: 'Linux Terminal Shortcuts That Save Hours Every Week', description: 'Ctrl+R reverse search, pushd/popd, process substitution, and brace expansion — all in 60 seconds each.', siteName: 'tiktok.com', categoryName: 'TikTok', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-01-20T21:00:00Z', tags: ['tips', 'tools', 'productivity'], deletedAt: '2026-02-01T21:00:00Z' },
  { url: 'https://www.tiktok.com/@devproductivity/video/567890', title: 'Debugging Tricks Nobody Talks About', description: 'console.table, conditional breakpoints, performance.mark(), and Chrome DevTools network throttling tricks.', siteName: 'tiktok.com', categoryName: 'TikTok', notes: null, status: 'watching', isFavorite: false, createdAt: '2026-03-14T18:00:00Z', tags: ['tips', 'tools', 'frontend'] },
  { url: 'https://www.tiktok.com/@seniordev/video/678901', title: 'The 10x Developer Productivity Stack in 2026', description: 'AI coding assistants, custom VS Code snippets, dotfiles strategy, and the tools that eliminate friction.', siteName: 'tiktok.com', categoryName: 'TikTok', notes: null, status: 'unread', isFavorite: false, createdAt: '2026-05-09T20:00:00Z', tags: ['productivity', 'tools', 'ai'] },

  // ── Other (4 links) ─────────────────────────────────────
  { url: 'https://excalidraw.com/', title: 'Excalidraw — Virtual Whiteboard for Developers', description: 'Sketch system diagrams, ERDs, and architecture diagrams that look hand-drawn. Perfect for async collaboration.', siteName: 'excalidraw.com', categoryName: 'Other', notes: 'Use for system design prep', status: 'watching', isFavorite: true, createdAt: '2026-04-20T10:00:00Z', tags: ['tools', 'design', 'productivity'] },
  { url: 'https://ray.so/', title: 'Ray.so — Beautiful Code Screenshots', description: 'Paste code and export beautiful images for blog posts, tweets, and slide decks. Supports syntax highlighting.', siteName: 'ray.so', categoryName: 'Other', notes: null, status: 'read', isFavorite: true, createdAt: '2025-09-05T11:00:00Z', tags: ['tools', 'design'] },
  { url: 'https://transform.tools/', title: 'Transform.tools — Code Conversion Swiss Army Knife', description: 'Convert JSON to TypeScript, SVG to JSX, CSS to JS, and more. Dozens of transformers, all in the browser.', siteName: 'transform.tools', categoryName: 'Other', notes: null, status: 'read', isFavorite: false, createdAt: '2025-10-12T14:00:00Z', tags: ['tools', 'frontend'] },
  { url: 'https://web.dev/explore/performance', title: 'Web.dev — Performance Learning Path', description: 'Google\'s curated learning path for Core Web Vitals, loading performance, rendering, and runtime efficiency.', siteName: 'web.dev', categoryName: 'Other', notes: 'Go through before next perf sprint', status: 'watching', isFavorite: false, createdAt: '2026-05-28T09:00:00Z', tags: ['performance', 'frontend', 'docs'] },
]

/** Only ever call this for the known local dev/test account -- see VaultContext.unlock(). */
export async function seedMockLinks(dek: CryptoKey): Promise<void> {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return

  const tagIds = await syncTagsByName(MOCK_TAG_NAMES, dek)
  const tagIdByName = new Map(MOCK_TAG_NAMES.map((name, i) => [name, tagIds[i]]))

  const categories = await getCategories(dek)
  const categoryIdByName = new Map(categories.map(c => [c.name, c.id]))

  const rows = await Promise.all(MOCK_LINKS.map(async link => {
    const content: LinkContent = {
      url: link.url,
      title: link.title,
      description: link.description,
      site_name: link.siteName,
      image_url: null,
      duration: null,
      notes: link.notes,
    }
    const encoded = await toEncryptedColumns<LinkContent>(content, dek)
    const url_fingerprint = await hmacFingerprint(link.url, dek)
    return {
      user_id: user.id,
      ...encoded,
      url_fingerprint,
      category_id: categoryIdByName.get(link.categoryName) ?? null,
      status: link.status,
      is_favorite: link.isFavorite,
      created_at: link.createdAt,
      updated_at: link.createdAt,
      deleted_at: link.deletedAt ?? null,
    }
  }))

  const { data: inserted, error } = await supabase.from('links').insert(rows).select('id')
  if (error || !inserted) return

  const linkTagRows = inserted.flatMap((row, i) =>
    MOCK_LINKS[i].tags.map(tagName => ({ link_id: row.id, tag_id: tagIdByName.get(tagName) })).filter(pair => pair.tag_id)
  )
  if (linkTagRows.length > 0) {
    await supabase.from('link_tags').insert(linkTagRows as { link_id: string; tag_id: string }[])
  }
}
